#pragma once

#include <string>
#include <array>

#include "XFL/DOM/DOMElement.h"

namespace Animate::DOM
{
	class FLDocument : public DOMElement
	{
	public:
		enum class Attributes : uint32_t
		{
			BackgroundColor,
			BackgroundAlpha,
			PasteboardColorCheck,
			Width,
			Height,
			FrameRate,
			CurrentTimeline,
			XflVersion,
			CreatorInfo,
			Platform,
			VersionInfo,
			MajorVersion,
			MinorVersion,
			BuildNumber,
			GridSpacingX,
			GridSpacingY,
			GridColor,
			GridSnapAccuracy,
			GridSnapTo,
			GuidesColor,
			GuidesLocked,
			GuidesSnapAccuracy,
			GuidesSnapTo,
			GuidesVisible,
			GridVisible,
			RulerVisible,
			PixelSnap,
			BitmapSnap,
			SnapAlign,
			SnapAlignBorder,
			SnapAlignBorderSpacing,
			SnapAlignHorizontalCenter,
			SnapAlignHorizontalSpacing,
			SnapAlignVerticalCenter,
			SnapAlignVerticalSpacing,
			ObjectsSnapTo,
			NextSymbolIdentifier,
			NextMediaIdentifier,
			NextTextFieldIdentifier,
			BreakPointCount,
			PinnedBrushSizes,
			PinnedEraserSizes,
			TimelineHeight,
			TimelineLabelWidth,
			HasPostProcessor,
			PostProcessorName,
			AdjustViewAngle3D,
			ViewAngle3D,
			VanishingPoint3DX,
			VanishingPoint3DY,
			PreviewFrame,
			TemplateFilename,
			TemplateDescription,
			SharedLibraryURL,
			ExportComponentSchemasToSwf,
			RulerUnitType,
			PreviewMode,
			TabOrderMode,
			HasLanguagePanelData,
			LanguageAvailableIndex,
			LanguageAvailableList,
			LanguageURL,
			LanguageDefault,
			LanguageForStage,
			LanguageAutoDetect,
			LanguageStringReplaceMethod,
			UseCarbonLineSpacing,
			NextSceneIdentifier,
			NextItemIdentifier,
			PostProcessorGUID,
			PostProcessorHRef,
			ViewOptionsAnimationControlVisible,
			ViewOptionsButtonsActive,
			ViewOptionsPasteBoardView,
			ViewOptionsLivePreview,
			PlayOptionsPlayLoop,
			PlayOptionsPlayPages,
			PlayOptionsPlayFrameActions,
			PlayOptionsPlaySounds,
			AccName,
			Description,
			Shortcut,
			TabIndex,
			Silent,
			ForceSimple,
			AutoLabeling,
			HasAccessibleData,
			TabRulerVisible,
			AutoSaveEnabled,
			AutoSaveIntervalMinutes,
			AutoSaveHasPrompted,
			ScaleContentWithStage,
			FiletypeGUID,
			FiletypeName,
			FileGUID
		};

		static inline std::array AttributeNames =
		{
			"backgroundColor",
			"backgroundAlpha",
			"pasteboardColorCheck",
			"width",
			"height",
			"frameRate",
			"currentTimeline",
			"xflVersion",
			"creatorInfo",
			"platform",
			"versionInfo",
			"majorVersion",
			"minorVersion",
			"buildNumber",
			"gridSpacingX",
			"gridSpacingY",
			"gridColor",
			"gridSnapAccuracy",
			"gridSnapTo",
			"guidesColor",
			"guidesLocked",
			"guidesSnapAccuracy",
			"guidesSnapTo",
			"guidesVisible",
			"gridVisible",
			"rulerVisible",
			"pixelSnap",
			"bitmapSnap",
			"snapAlign",
			"snapAlignBorder",
			"snapAlignBorderSpacing",
			"snapAlignHorizontalCenter",
			"snapAlignHorizontalSpacing",
			"snapAlignVerticalCenter",
			"snapAlignVerticalSpacing",
			"objectsSnapTo",
			"nextSymbolIdentifier",
			"nextMediaIdentifier",
			"nextTextFieldIdentifier",
			"breakPointCount",
			"pinnedBrushSizes",
			"pinnedEraserSizes",
			"timelineHeight",
			"timelineLabelWidth",
			"hasPostProcessor",
			"postProcessorName",
			"adjustViewAngle3D",
			"viewAngle3D",
			"vanishingPoint3DX",
			"vanishingPoint3DY",
			"previewFrame",
			"templateFilename",
			"templateDescription",
			"sharedLibraryURL",
			"exportComponentSchemasToSwf",
			"rulerUnitType",
			"previewMode",
			"tabOrderMode",
			"hasLanguagePanelData",
			"languageAvailableIndex",
			"languageAvailableList",
			"languageURL",
			"languageDefault",
			"languageForStage",
			"languageAutoDetect",
			"languageStringReplaceMethod",
			"useCarbonLineSpacing",
			"nextSceneIdentifier",
			"nextItemIdentifier",
			"postProcessorGUID",
			"postProcessorHRef",
			"viewOptionsAnimationControlVisible",
			"viewOptionsButtonsActive",
			"viewOptionsPasteBoardView",
			"viewOptionsLivePreview",
			"playOptionsPlayLoop",
			"playOptionsPlayPages",
			"playOptionsPlayFrameActions",
			"playOptionsPlaySounds",
			"accName",
			"description",
			"shortcut",
			"tabIndex",
			"silent",
			"forceSimple",
			"autoLabeling",
			"hasAccessibleData",
			"tabRulerVisible",
			"autoSaveEnabled",
			"autoSaveIntervalMinutes",
			"autoSaveHasPrompted",
			"scaleContentWithStage",
			"filetypeGUID",
			"filetypeName",
			"fileGUID"
		};

		static const char* GetAtributeName(Attributes attribute)
		{
			return AttributeNames[(uint32_t)attribute];
		}

	public:
		virtual ElementTag GetTag()
		{
			return ElementTag::DOMDocument;
		}

		void SetAttributes(XFL::XFLWriter& writer)
		{
			writer.WriteAttr(
				GetAtributeName(Attributes::FrameRate),
				frameRate
			);
		}

	public:
		const char* xflVersion;
		int frameRate;
	};
}